databases:
  - name: Garment_DB
    databaseName: garment_db
    user: Garment
    region: singapore

services:
  - type: web
    name: Garment
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Garment_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

